name: 'Deploy'
on:
  workflow_run:
    workflows: [ 'Setup' ]                     # runs after CI workflow
    types:
      - completed
  push:
    branches:
      - main
      - hotfix/*
  pull_request:
    branches:
      - main
      - hotfix/*
jobs:
  deploy:
    continue-on-error: false
    name: Deploy to Firebase Functions
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: jsryudev/deploy-firebase-functions@v0.0.2
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
          FIREBASE_PROJECT: ${{ secrets.FIREBASE_PROJECT_ID }}
