name: Setup
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  contents: read
  actions: read
  checks: write

jobs:
  main:
    strategy:
      matrix:
        node-version: [ '18.x', '20.x' ]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install Supertest, mocha, jest, chai
        run: npm i -g -D supertest mocha jest chai

      - name: Install Deps
        run: npm install

      - name: Build
        run: npm run build --if-present

      - name: Test
        run: npm test

      - name: Upload artifact
        uses: actions/upload-artifact@v3  # upload test results
        with:
          name: test-results
          path: coverage/clover.xml

      - name: Test Report
        uses: dorny/test-reporter@v1
        continue-on-error: true
        if: success() || failure()    # run this step even if previous step failed
        with:
          name: test-results            # Name of the check run which will be created
          path: coverage/clover.xml      # Path to test results
          reporter: jest-junit          # Format of test results

  deploy:
    needs: main
    name: Deploy to Firebase Functions
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: jsryudev/deploy-firebase-functions@v0.0.2
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
          FIREBASE_PROJECT: ${{ secrets.FIREBASE_PROJECT_ID }}
