name: Setup
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  contents: read
  actions: read
  checks: write

jobs:
  main:
    strategy:
      matrix:
        node-version: [ '18.x', '20.x' ]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install Supertest, mocha, jest, chai
        run: npm i -g -D supertest mocha jest chai

      - name: Install Deps
        run: npm install

      - name: Build
        run: npm run build --if-present

      - name: Test
        run: npm test

  deploy:
    needs: main
    name: Deploy to Firebase Functions
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: jsryudev/deploy-firebase-functions@v0.0.2
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
          FIREBASE_PROJECT: ${{ secrets.FIREBASE_PROJECT_ID }}

  report:
    needs: main
    runs-on: ubuntu-latest
    steps:
      - name: Test Results
        uses: dorny/test-reporter@v1.7.0
        if: success() || failure()
        with:
          name: JEST Tests
          path: ${{ github.workspace }}/reports/test-results.json
          reporter: jest-junit
