name: Setup
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions: read-all

jobs:
  main:
    permissions:
      contents: 'read'
      id-token: 'write'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js 18.x
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'

      - name: Install Supertest, mocha, jest, chai
        run: npm i -g -D supertest mocha jest chai

      - name: Install Deps
        run: npm install

      - name: Build
        run: npm run build --if-present

      - name: Test
        run: npm test

      - name: Upload artifact
        uses: actions/upload-artifact@v3  # upload test results
        with:
          name: test-results
          path: coverage/clover.xml

      - name: Test Report
        uses: ArtiomTr/jest-coverage-report-action@v2.2.6
        with:
          github-token: ${{ secrets.GH_TOKEN }}

  deploy:
    needs: main
    name: Deploy to Firebase Functions
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Deploy to Firebase
        uses: sws2apps/firebase-deployment@main
        with:
          workloadIdentityProvider: ${{ secrets.WORKLOAD_IDENTITY_PROVIDER }}
          serviceAccount: ${{ secrets.SERVICE_ACCOUNT }}
          node-version: 18
          function: true
          hosting: false
          project: ${{ secrets.FIREBASE_PROJECT_ID }}
