name: Test Report
on:
  workflow_run:
    workflows: ["Setup"]
    types:
      - completed
  push:
    branches:
      - main
      - hotfix/*
  pull_request:
    branches:
      - main
      - hotfix/*
permissions:
  contents: read
  actions: read
  checks: write
jobs:
  report:
    runs-on: ubuntu-latest
    steps:
      - name: Test Results
        uses: dorny/test-reporter@v1.7.0
        if: success() || failure()
        with:
          name: JEST Tests
          path: ${{ github.workspace }}/reports/test-results.json
          reporter: jest-junit
